spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/formlaez
    username: postgres
    password: 6*[)s8G'Vs#rQUsm
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/formini-so
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

formlaez:
  aws:
    credentials:
      accessKey: AKIASWNAGJRE76HMHPP2
      secretKey: 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
    s3:
      bucketName: formini

  firebase:
    serviceAccountJsonFile: classpath:certs/firebase.json

  paddle:
    publicKey: classpath:certs/paddle.pub
    plusPlanId: 816905
    businessPlanId: 816906
    vendorId: 166197
    vendorAuthCode: 3e917f0168b472e47cdf98e0d1a3b7e38aba8ed5cf055cc133
    apiBaseUrl: https://vendors.paddle.com/api/2.0

  billing-plan:
    plans:
      - code: Free
        price: 0
        formLimit: 3
        documentMergePerMonth: 10
        submissionPerMonth: 100
        fileStorageLimit: 100000
        workspaceMember: 1

      - code: Plus
        price: 10
        formLimit: 20
        documentMergePerMonth: 100
        submissionPerMonth: 500
        fileStorageLimit: 1000000000
        workspaceMember: 2

      - code: Business
        price: 40
        formLimit: 200
        documentMergePerMonth: 500
        submissionPerMonth: 2000
        fileStorageLimit: 5000000000
        workspaceMember: 5

  scheduler:
    subscription-expired:
      cron: 0 0 8,14 * * *

  sendgrid:
    apiKey: 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
    defaultSender: hello@formini.so
    signUpTemplateId: d-9d73823e3a1b4368b8e2ac0e39fadf73
    welcomeTemplateId: d-afb1172187904ca1bfb665fdca58c246
