spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formlaez
    username: postgres
    password: postgres
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/formini-so
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
  jpa:
    show-sql: false

formlaez:
  aws:
    credentials:
      accessKey: AKIASWNAGJRE4MK63Q7B
      secretKey: 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
    s3:
      bucketName: formlaez-dev

  firebase:
    serviceAccountJsonFile: classpath:certs-local/firebase.json

  paddle:
    publicKey: classpath:certs-local/paddle.pub
    plusPlanId: 47512
    businessPlanId: 47513
    vendorId: 11046
    vendorAuthCode: 61b8f9c561097c0948e22533458f63576afc35bfe633c9adfc
    apiBaseUrl: https://sandbox-vendors.paddle.com/api/2.0

  billing-plan:
    plans:
      - code: Free
        price: 0
        formLimit: 5
        documentMergePerMonth: 25
        submissionPerMonth: 100
        fileStorageLimit: 100000000
        workspaceMember: 1

      - code: Plus
        price: 25
        formLimit: 20
        documentMergePerMonth: 100
        submissionPerMonth: 500
        fileStorageLimit: 1000000000
        workspaceMember: 2

      - code: Business
        price: 40
        formLimit: 100
        documentMergePerMonth: 500
        submissionPerMonth: 2000
        fileStorageLimit: 5000000000
        workspaceMember: 5

  scheduler:
    subscription-expired:
      cron: 0 0 8,14 * * *

  sendgrid:
    apiKey: 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
    defaultSender: hello@formini.so
    signUpTemplateId: d-9d73823e3a1b4368b8e2ac0e39fadf73
    welcomeTemplateId: d-afb1172187904ca1bfb665fdca58c246

logging:
  level:
    root: info