spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/formlaez
    username: postgres
    password: 6*[)s8G'Vs#rQUsm
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${formlaez.authUrl}

formlaez:
  domainName: formini.so
  authUrl: https://auth.${formlaez.domainName}
  appUrl: https://app.${formlaez.domainName}
  client:
    auth:
      baseUrl: http://formlaez-auth-server:9000
      authorization: Basic Zm9ybWxhZXotd2ViOjEyMzQ1NjdhQCM=
      redirectUri: ${formlaez.appUrl}/login/code

    authInternal:
      baseUrl: http://formlaez-auth-server:9000/internal
      authorization: Basic Zm9ybWxhZXotc2VydmljZXM6ZjBybUxAZXo=

  basic-auth:
    users:
      - username: formlaez-auth
        password: "{bcrypt}$2a$10$ZkVufhbhMwdbAg74OIB0FuhjDUMsZWB3ses4NydeqBh8KYdLluVMa"
        roles: "Admin"

  aws:
    s3:
      bucketName: formlaez-dev
      credentials:
        accessKey: AKIASWNAGJRE4MK63Q7B
        secretKey: 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

  paddle:
    publicKey: classpath:certs/paddle.pub
    plusPlanId: 47512
    businessPlanId: 47513
    vendorId: 11046
    vendorAuthCode: 61b8f9c561097c0948e22533458f63576afc35bfe633c9adfc
    apiBaseUrl: https://sandbox-vendors.paddle.com/api/2.0

  sendGrid:
    secretKey: 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

  billing-plan:
    plans:
      - code: Free
        productId: -1
        price: 0
        formLimit: 5
        documentMergePerMonth: 25
        submissionPerMonth: 100
        fileStorageLimit: 100000000
        workspaceMember: 1

      - code: Plus
        productId: 47512
        price: 25
        formLimit: 20
        documentMergePerMonth: 100
        submissionPerMonth: 500
        fileStorageLimit: 1000000000
        workspaceMember: 2

      - code: Business
        productId: 47513
        price: 40
        formLimit: 100
        documentMergePerMonth: 500
        submissionPerMonth: 2000
        fileStorageLimit: 5000000000
        workspaceMember: 5

  scheduler:
    subscription-expired:
      cron: 0 0 8,14 * * *
