spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formlaez
    username: postgres
    password: postgres
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  jpa:
    show-sql: false

formlaez:
  client:
    auth:
      baseUrl: http://localhost:9000
      authorization: Basic Zm9ybWxhZXotd2ViOjEyMzQ1NjdhQCM=
      redirectUri: http://127.0.0.1:3000/login/code

  basic-auth:
    users:
      - username: formlaez-auth
        password: "{bcrypt}$2a$10$ZkVufhbhMwdbAg74OIB0FuhjDUMsZWB3ses4NydeqBh8KYdLluVMa"
        roles: "Admin"

  aws:
    s3:
      bucketName: formlaez-dev
      credentials:
        accessKey: AKIASWNAGJRE4MK63Q7B
        secretKey: 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

logging:
  level:
    root: info